easy_admin:
    site_name: 
        <div style="display:flex;align-items:center;">
        <img width="50" src="https://upload.wikimedia.org/wikipedia/commons/f/f3/Flag_of_Russia.svg">
        <span> <strong>Russe</strong> à la Datcha </span>
        </div> 