easy_admin:
    design:
        #brand_color: "#ff0000"
        #assets:
        # all kinds of assets are supported and linked accordingly
        #    css:
        #        - "css/admin.css"
        #    js:
        #        - '/bundles/user/js/admin4.js'
