easy_admin:
    entities:
        User:
            class: App\Entity\User
            list:
                actions: 
                    - { name: "edit", label: false, icon: "pencil", css_class: "btn btn-primary" }
                    - { name: "delete", label: false, icon: "trash", css_class: "btn btn-danger" } 